url: http://gregkn.github.io/
baseurl: ""

# Site settings
title: Greg KN
email: greg@gregkn.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FF4F00
  secondary: C0362C
  secondary-dark: 333
  blue: 00BFFF
  darkerblue: 07A4D9

# Team names, titles and social links
people:
- name:
  pic: 1
  position:
  social:

- name: Greg Karp-Neufeld
  pic: 2
  position:
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/gregkn
  - title: envelope
    url: mailto:greg@gregkn.com

- name:
  pic: 3
  position:
  social:


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/gregkn

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
