url: http://gregkn.github.io/
baseurl: ""

# Site settings
title: Greg KN
email: greg@gregkn.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: 
  pic: 1
  position:
  social:

- name: Greg Karp-Neufeld
  pic: 2
  position:
  social:
  - title: twitter
    url: http://twitter.com/gregkn10
  - title: linkedin
    url: https://www.linkedin.com/in/gregkn
  - title: facebook
    url: https://www.facebook.com/gregkn
  - title: envelope
    url: mailto:greg@gregkn.com

- name:
  pic: 3
  position:
  social:


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/gregkn10
  - title: linkedin
    url: https://www.linkedin.com/in/gregkn
  - title: facebook
    url: https://www.facebook.com/gregkn

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty